### ISSUE TITLE
date.c:(.text.date_main+0x2b6): undefined reference to `stime'

### ISSUE THREAD

**Issue by adrianmace** [RIPE-NCC/ripe-atlas-software-probe#51] opened 2020-09-27 09:54 UTC
![image](https://user-images.githubusercontent.com/5071859/94361921-155ade00-00fb-11eb-85fa-3941c2b6481e.png)

Seems to be occurring on both `master` and `devel` as of today's commits.

Ubuntu 20.04 LTS.

**Comment by phicoh** [comment] 2020-09-28 09:07
Please check the git commit in probe-busybox. It should be 1c80e1953a5794660d39c731d0fdac77f34aed9b, which is version where stime is removed.

**Comment by snh** [comment] 2020-09-28 09:42
@phicoh https://github.com/RIPE-NCC/ripe-atlas-probe-busybox/commit/fb8bc976a326f894b16e859124dd27e865fd3ccc appears to be the current tip of `master` (the default branch), with only `devel` containing https://github.com/RIPE-NCC/ripe-atlas-probe-busybox/commit/1c80e1953a5794660d39c731d0fdac77f34aed9b.

Is this going to move to `master` soon so that this will be picked up automatically?

**Comment by phicoh** [comment] 2020-09-28 09:47
The problem is that when we do a release, we sign the centos binaries (and the firmware for the hardware probes). Due to corona, nobody is going to the office to do the signing. And the changes are not really big enough. Though I understand that the current situation is annoying for people running ubuntu. I have to see if we can do a release that is just source code.

**Comment by h289072** [comment] 2021-03-13 17:04
So is there a workaround? I've deliberately upgraded to ubuntu 20.04 before installing the software probe.

**Comment by h289072** [comment] 2021-03-13 17:41
> So is there a workaround? I've deliberately upgraded to ubuntu 20.04 before installing the software probe.

Ah ok... checking out 142acd3673051769debd8fd7261b121fb7b4f609 will do it

**Comment by PhilipHomburg** [comment] 2021-09-16 14:16
Fixed in master

**Closed by PhilipHomburg** 2021-09-16 14:16 UTC
