### ISSUE TITLE
rptaddrs segfault

### ISSUE THREAD

**Issue by lehha** [RIPE-NCC/ripe-atlas-software-probe#49] opened 2020-08-25 18:34 UTC
Probe runned at Docker, and have segfault in /var/log/messages:

Aug 25 18:30:44 srv kernel: rptaddrs[17146]: segfault at 7fff8c115075 ip 00007fdf56454820 sp 00007fff8c113f88 error 4 in libc-2.28.so[7fdf5631a000+148000]
Aug 25 19:36:52 srv kernel: rptaddrs[17633]: segfault at 7ffe3db0d015 ip 00007f83ac166820 sp 00007ffe3db0bf28 error 4 in libc-2.28.so[7f83ac02c000+148000]
Aug 25 20:49:03 srv kernel: rptaddrs[18234]: segfault at 7fff0c7411a5 ip 00007f0c6a2c8820 sp 00007fff0c7400b8 error 4 in libc-2.28.so[7f0c6a18e000+148000]

Software Probe also on another host in Docker:
Aug 25 20:02:01 srv2 kernel: rptaddrs[24305]: segfault at 7fffa024b045 ip 00007f699f454201 sp 00007fffa0249f48 error 4 in libc-2.28.so[7f699f3d4000+148000]
Aug 25 20:08:01 srv2 kernel: rptaddrs[24338]: segfault at 7ffe12109295 ip 00007f992b5bb201 sp 00007ffe12108198 error 4 in libc-2.28.so[7f992b53b000+148000]
Aug 25 20:53:01 srv2 er1 kernel: rptaddrs[24607]: segfault at 7fff60238055 ip 00007fb1507f0201 sp 00007fff60236f58 error 4 in libc-2.28.so[7fb150770000+148000]

**Comment by PhilipHomburg** [comment] 2020-08-26 10:21
Can you run something like the following command and capture the output?

strace -s 8000 /usr/local/atlas/bb-13.3/bin/rptaddrs -c /home/atlas/data/new/ripadddrs-cache

**Comment by lehha** [comment] 2020-08-26 14:23
There are no strace in docker image. If run without it:
rptaddrs: error writing to /': Success

![изображение](https://user-images.githubusercontent.com/4051362/91315834-d0bce980-e7c0-11ea-8e5c-a9c21261abe0.png)

**Comment by PhilipHomburg** [comment] 2020-08-26 17:00
That is certainly a bug, but not the one you triggered originally. Maybe you can find an strace for your docker container and run that?

**Comment by lehha** [comment] 2020-08-27 07:28
Segfault does not occur immediately, approximately every 20-40 minutes. Strace need to run once or run before the Segfault appears?

**Comment by PhilipHomburg** [comment] 2020-08-27 10:32
Best is to capture the one with the segfault

**Comment by menghoumenghou** [comment] 2020-10-26 02:58
I tried to run the strace command but apparently it was not installed in the container. 
However I found the path for the file used in the strace command is actually not in /home/atlas/data/new/, instead it is in /var/atlas-probe/data/new.
Also I could not see ripaddrs-cache file in this directory, I can only see below files:
![image](https://user-images.githubusercontent.com/20235458/97129518-0c9d0c80-177a-11eb-8fc7-ad2b22f6d376.png)
I guess the issue must happened before the file is generated.

**Comment by PhilipHomburg** [comment] 2020-10-26 10:01
Ah, that's right the path on software probes is different. In any case, please install strace in the container

**Comment by Jamesits** [comment] 2020-10-26 10:03
@menghoumenghou You can use the following command to install `strace` in the container if you are using my container:

```shell
apt-get update
apt-get install strace -y
```

**Comment by menghoumenghou** [comment] 2020-10-26 11:26
@Jamesits @PhilipHomburg 
Thank you, I have got the strace output below, please see if it helps.

[strace.log](https://github.com/RIPE-NCC/ripe-atlas-software-probe/files/5438459/strace.log)

**Comment by PhilipHomburg** [comment] 2020-10-26 17:02
There was no filename after the -c option. So probably something like this is needed:

mkdir -p /home/atlas/data/new
strace -s 8000 /usr/local/atlas/bb-13.3/bin/rptaddrs -c /home/atlas/data/new/ripadddrs-cache

**Comment by menghoumenghou** [comment] 2020-10-27 08:39
@PhilipHomburg 
Here you go, I have got both the output of strace and the generated file under /home/atlas/data/new


[ripadddrs-cache.new.log](https://github.com/RIPE-NCC/ripe-atlas-software-probe/files/5443953/ripadddrs-cache.new.log)
[straceoutput.txt](https://github.com/RIPE-NCC/ripe-atlas-software-probe/files/5443954/straceoutput.txt)

you may need to remove the .log suffix of ripadddrs-cache.new.log file.

**Comment by PhilipHomburg** [comment] 2020-10-27 13:32
It turned out the bug was due to lack of IPv6. On a normal linux install that never happens, so there were two tiny mistakes in the code that got triggered. I don't know why people are building new software without IPv6. Certainly for Atlas it is really bad to have docker images that only have IPv4. 

In any case, I fixed the bugs and push a new version to the devel branch.

**Comment by menghoumenghou** [comment] 2020-10-28 01:08
Thanks, I tried to enable IPv6 in docker and assigned a site local IPv6 address block FD00::/80 for docker to assign to containers. 
Right after I did those the segfault is gone and the report feature resumes to work. 

This works for me as my ISP doesn't assign IPv6 address block to me but for people who already got IPv6 addresses I believe there are better resolutions.

**Comment by aveao** [comment] 2020-10-28 18:33
I can confirm that the changes made to ripe-atlas-probe-busybox fixes this. I've built the `devel` branch of probe-busybox when deploying a probe, and that fixed the segfaults. FWIW, this was running under raspbian lite on a rpi0 on a legacy IPv4-only network.

**Comment by PhilipHomburg** [comment] 2020-10-28 19:52
I assume that the previous version also worked fine on raspbian. In general, linux distributions have at least an IPv6 address even if the network IPv4-only. It is only docker containers that absolutely no IPv6 at all.

**Comment by aveao** [comment] 2020-10-28 19:59
Ah, that might explain it.

In my case [the machine in question](https://twitter.com/warnvod/status/1321499561182040064) only has a ppp connection (created by NetworkManager when connecting to Internet through a USB modem) and a wireguard connection, and neither of them have IPv6 addresses.

![](https://elixi.re/i/l2zvzrsp.png)

That explains why this worked over wifi but failed when I moved it to a cellular-only network. This is very much an edge case.

**Comment by PhilipHomburg** [comment] 2020-10-28 20:03
That's interesting. I wonder why those interfaces don't have IPv6 link local. Maybe because ppp can explictly configure only IPv4. 

Though your loopback interface has ::1/128. 

In any case, it is good that the bug is fixed.

**Comment by PhilipHomburg** [comment] 2021-09-16 14:15
Master now refers to a busybox version that has this fixed.

**Closed by PhilipHomburg** 2021-09-16 14:15 UTC
